### ISSUE TITLE
[Feature] - New MAME core

### ISSUE THREAD

**Issue by OPNA2608** [BambooTracker/BambooTracker#262]
> #### Checklist
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

Just wanted to tip you off that MAME is currently working on rewriting their FM cores in a [new branch](https://github.com/mamedev/mame/commits/fmrewrite), including the YM2608 one. The rewrite is from what I heard intended to be (at least) sample-accurate & under the 3-clause BSD license.

It's prolly worth it to keep an eye out on this branch & an eventual merge into master so we can update to that version. :eyes:

**Comment by rerrahkr** [comment]
Thanks for your info! Since there are several bugs such as incorrect synthesis rate and SSG-EG (#93) in the current MAME emulation, I hope that they are solved in the new branch.

**Comment by freq-mod** [comment]
Just to let you know - this branch has been merged into master! :eyes:

**Comment by OPNA2608** [comment]
For tracking which files/commits were part of the rewrite, here's the PR: https://github.com/mamedev/mame/pull/7808
