### ISSUE TITLE
[Feature] - Effect that forces the note phase down to zero

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#301]
> #### Checklist
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---
## Requested Feature

The conclusion of [this issue](https://github.com/rerrahkr/BambooTracker/issues/292#issue-750259226) inspired me to ask for a new feature, an effect that forces the note phase to zero. I understand that you could start a release on the channel to use this effect on, but it may be infeasible to have all four operators reset at once.

Example:
`(0E/EE)xx: waits xx ticks to force the note phase to 0.`

**Comment by rerrahkr** [comment]
Thanks for your request. I won't be able to add more features for a while, but I'll keep it as a candidate for the next time we implement new effects.

**Comment by rerrahkr** [comment]
In d2e7c51d5ff13a06eab6b2fefb13b49f64073fe9, I added a new pattern effect `ESxx`: FM envelope reset which allow you to initialize FM envelope phase.

**Comment by Zexxerd** [comment]
I know it's been 23 days, but the build failed with the message `Maximum allowed artifact storage size of 90000 Mb will be exceeded.`

**Comment by rerrahkr** [comment]
Sorry, d2e7c51 cannot rebuild now due to be updated Artifacts retention policy.
Please check the latest commit in `master` e7c28a3a5f6a5607672e99aef1dd8f7cfd7540da which contains this feature:
https://ci.appveyor.com/project/rerrahkr/bambootracker/builds/39331875
