### ISSUE TITLE
[Windows] - Error when attempting to export a WAV for a file

### ISSUE THREAD

**Issue by Drillimation** [BambooTracker/BambooTracker#303]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When attempting to export a song, the following error message appears:

Failed to export to [path].
std::bad_alloc

## How to reproduce

1. Open any file.
2. Export a song to WAV
3. …

## System Information

- **Operating System**: Windows 10
- **BambooTracker Version**: 0.4.5

**Comment by rerrahkr** [comment]
Thanks for your report.
I can't see such a problem in my environment. Could you please take a screenshot of the error dialog in more detail? Also, if possible, could you attach the btm where the error occurs?

**Comment by Drillimation** [comment]
![Image of error](https://media.discordapp.net/attachments/764626333262675969/796357282396110868/unknown.png)

https://drive.google.com/file/d/1pUmpfolTjr9Epp1YIrLiQHN7_Odc15TY/view?usp=sharing

**Comment by rerrahkr** [comment]
Thank you, I was able to replicate it.
It seems that the memory copy when writing wav is failed. I'll check more details.

**Comment by rerrahkr** [comment]
I modified the handling of binaries at 6281ac1. I hope it solves this issue.
