### ISSUE TITLE
[Windows] - WAV Exports incorrectly

### ISSUE THREAD

**Issue by Drillimation** [BambooTracker/BambooTracker#328]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When exporting a WAV, the entire song, including the number of loops, incorrectly exports, resulting in the song ending prematurely in the final file.

## How to reproduce

1. Open any file.
2. Export the song as a WAV file.
3. After the export, the waveform continues animating until the stop button is clicked, and whenever the song is opened in Audacity or any other media player, the entire song isn't there.

## System Information

- **Operating System**: Windows 10 
- **BambooTracker Version**: v0.4.6 
- **Build Type**:

**Comment by OPNA2608** [comment]
I'm experiencing the same thing under Linux. To clarify, the WAV export continues running despite the export window closing itself very early into the process. The WAV should actually record fine if you wait for the song to finish recording (as indicated by the oscilloscope seizing activity). This seems to be a problem with the export menu disassociating itself from the actual exporting?

**Comment by rerrahkr** [comment]
Thanks for your reports. I fixed the song step counter in e9d9ad407ee096da3cb3898da0b6bac4faddca6c which will solve this issue.
