### ISSUE TITLE
[Feature] - Ability to make a pattern in the order list unique.

### ISSUE THREAD

**Issue by Mugenri** [BambooTracker/BambooTracker#329]
> #### Checklist

> - [X] I'm requesting exactly 1 feature with this issue.
> - [X] This feature hasn't already been requested.
> - [X] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

Instead of having to find the next empty pattern, copy the desired pattern, then paste it in the new one, a shortcut could be added in the order list to make a selected pattern unique from the pattern it's currently a copy of.

**Comment by rerrahkr** [comment]
You can copy orders to empty ones as unique number using copy, paste and "Clone patterns":

https://user-images.githubusercontent.com/26477882/107850175-d75d1d00-6e43-11eb-96da-8b7afc6e23c5.mp4

"Clone patterns" behaves like applying "Duplicate order" only to selected tracks.
