### ISSUE TITLE
[Feature] - Make right clicking a pattern in the order list highlight it.

### ISSUE THREAD

**Issue by Mugenri** [BambooTracker/BambooTracker#333]
> - [X] I'm requesting exactly 1 feature with this issue.
> - [X] This feature hasn't already been requested.
> - [X] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

When trying to clone a single pattern in the order list you have to click and drag a little bit so that it highlights the singular pattern. QoL change would make it so that right clicking on the pattern would highlight the order you clicked on.

**Comment by rerrahkr** [comment]
Thanks for your request. I changed its behavior in fdb048e67c7fdc18b709b55fee5300cf90a611fb.
