### ISSUE TITLE
[Windows] Trying to undo a change instrument operation performed on an entire pattern doesn't work correctly.

### ISSUE THREAD

**Issue by Mugenri** [BambooTracker/BambooTracker#341]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Using Alt+S after selecting an entire pattern with Ctrl+A+A and then doing Ctrl+Z changes every instrument in the pattern to a single instrument instead of correctly undoing the replace instrument operation for each channel. Each channel has to be given the correct instruments manually.

## How to reproduce

See above.

## System Information

- **Operating System**:  Windows 10
- **BambooTracker Version**: Release v0.4.6
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thanks for your report. I fixed it in dcff2146ef13e1d52c84db418f0300658f96f638.
