### ISSUE TITLE
[Feature] - Ability to change the spelling of notes

### ISSUE THREAD

**Issue by wildmatsu** [BambooTracker/BambooTracker#345]
> #### Checklist
> 
> - [ x ] I'm requesting exactly 1 feature with this issue.
> - [ x ] This feature hasn't already been requested.
> - [ x ] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

I would like to be able to change the spelling of notes, rather than have every white piano key be spelled as a natural and every black piano key spelled as a sharp. I would find this feature useful when working in flat key signatures. For example, I'd rather the notes of Db Major be spelled as Db, Eb, F, Gb, Ab, Bb, C, Db instead of C#, D#, F, F#, G#, A#, C, C#. 

DN-Famitracker has some support for this. The implementation in DN-Famitracker is a bit naive, but is nonetheless a major QOL upgrade for me over not having it at all. Basically, there is a global toggle whether to spell black keys as sharps or flats. If even this much is implemented, I will be happy, but there is room for improvement. 

One major flaw in this scheme is that it must be manually changed when switching between a song with a sharp key and one with a flat key--or two different sections of a single song that changes keys. There are also times when you want both sharps and flats in a single key--for instance, Bb and C# in the key of D minor.

Additionally, it's not unheard of to see notes like E#, Fb, B#, Cb, or double sharps and double flats in sheet music. Ideally, I'd like all of those to be supported, but it'd be a lot of effort for something that is only rarely useful. It's probably reasonable to draw the line here, but I thought I'd mention it, at least.

Given what I've discussed above, I'd like to propose several different potential ways to address the handling of note spellings:

- Do what DN-Famitracker does, and make it a global setting whether to display black keys as all sharps or all flats. (Deficient in many ways, but significantly better than nothing.)
- As above, but also add a shortcut that toggles that global setting so that users can instantly switch between the two on the fly. (A very simple change that mitigates MANY of the problems with the previous solution, and avoids much of the complexity of the following solutions.)
- Add a per-song setting for whether to spell black keys as sharps or flats. (A significant improvement over the first solution, and not much more complicated to implement, but still has some deficiencies, and requires changing the save format of the song to support an additional global setting.)
- Add an effect that changes the way black keys are spelled through the end of the song or until the next time that effect is used. Either "all sharp" or "all flat." (A minor improvement over the above, and wouldn't necessitate changing the save format.)
- Add an effect that sets the key of the piece, and sets each note to the "most reasonable" spelling for that key. For instance, in D minor, this would involve the spellings Bb and C#. If you decide to pursue this solution, and you're not sure what I mean by "the most reasonable spellings," I'd be happy to explain further.
- Allow the user to manually set the spelling of each note, perhaps with the shortcut keys Ctrl+F5 and Ctrl+F6. For example, C could be spelled as C, B#, or Dbb. (The most complex but most complete solution, but would involve significantly altering the save format, and would be overkill for most users.)

Thank you for your time and consideration.

**Comment by wildmatsu** [comment]
Note: I have submitted [a similar request to DN-Famitracker](https://github.com/Gumball2415/Dn-FamiTracker/issues/41).  I mention this only because BambooTracker shares a lot of code with DN-Famitracker, and hopefully it is possible to avoid duplicated effort.

**Comment by rerrahkr** [comment]
Thanks for your request. I think it would be nice to be able to change the spelling for each order list. It is also necessary to think about how to display the double sharp / flat notation with 1 character due to width limitation.

**Comment by wildmatsu** [comment]
Double sharp is easy: Cx. As for double flat, though, I don't know.

**Comment by rerrahkr** [comment]
> * Add an effect that sets the key of the piece, and sets each note to the "most reasonable" spelling for that key. For instance, in D minor, this would involve the spellings Bb and C#. If you decide to pursue this solution, and you're not sure what I mean by "the most reasonable spellings," I'd be happy to explain further.

I am trying to implement it in this way.
I don't know much about music theory, so I would like to know something about it.

I know that D minor is:

| D minor  | 1   | 2   | 3   | 4   | 5   | 6       | 7       |
| -------- | --- | --- | --- | --- | --- | ------- | ------- |
| Natural  | D   | E   | F   | G   | A   | B♭      | C       |
| Harmonic | D   | E   | F   | G   | A   | B♭      | C♯      |
| Melodic  | D   | E   | F   | G   | A   | B or B♭ | C♯ or C |

However, the notation of pitch, which is represented by an occasional sign, is not clear in the score.
I thought  D, E♭, E, F, F♯, G, G♯, A, B♭, B, C, C♯, is it correct?

I'm also confused about the notation of note names in other keys.
If you can, please let me know the key and note names that you think are appropriate.

**Comment by wildmatsu** [comment]
Hello Rerrah,

Thanks a bunch for working on this!

> I thought D, E♭, E, F, F♯, G, G♯, A, B♭, B, C, C♯, is it correct?

These are the note names I would use for the key of D, yes.

> I'm also confused about the notation of note names in other keys.
> If you can, please let me know the key and note names that you think are appropriate.

I'll try to briefly explain the high-level concept first. If you aren't familiar with all the music theory jargon I'm using, then feel free to ask me to explain anything; I'm happy to help.

The relationship between D and D♯ is an augmented unison. The relationship between D and E♭ is a minor second. Augmented unisons are used occasionally, but minor seconds are much more common. In general, it's more common to see perfect intervals, major intervals, and minor intervals than it is to see augmented or diminished intervals. Using this guiding principle alone, we can settle on the best name for 11 of the 12 notes in any key immediately. We should use these names: P1, m2, M2, m3, M3, P4, ??, P5, m6, M6, m7, M7, (P8).

The only note remaining to be named is the tritone, which has no perfect, major, or minor name; it can only be the augmented fourth or diminished fifth. Between these two choices, I believe the augmented fourth is the more useful name. Lydian is used somewhat often as compared with Locrian which is almost never used. Furthermore, the commonly-used secondary dominant V/V involves a sharp four scale degree. There are use cases for a flat five, but I'm comfortable saying the augmented fourth is more common and useful.

Thus, the note names you gave for D minor do not just work for D minor, work for MANY scales built on D: the major scale, all three flavors of minor (natural, harmonic, melodic) and all of the other modes of the major scale except Locrian.

Anyway, I produced a table of the best note names for each key. The top row represents the number of semitones from the root of the key. The second row represents my chosen name for that interval. 

|    | 0  | 1   | 2  | 3   | 4  | 5   | 6  | 7  | 8   | 9  | 10  | 11 | 12 |
|----|----|-----|----|-----|----|-----|----|----|-----|----|-----|----|----|
|    | P1 | m2  | M2 | m3  | M3 | P4  | A4 | P5 | m6  | M6 | m7  | M7 | P8 |
| C  | C  | Db  | D  | Eb  | E  | F   | F# | G  | Ab  | A  | Bb  | B  | C  |
| C# | C# | D   | D# | E   | E# | F#  | Fx | G# | A   | A# | B   | B# | C# |
| Db | Db | Ebb | Eb | Fb  | F  | Gb  | G  | Ab | Bbb | Bb | Cb  | C  | Db |
| D  | D  | Eb  | E  | F   | F# | G   | G# | A  | Bb  | B  | C   | C# | D  |
| D# | D# | E   | E# | F#  | Fx | G#  | Gx | A# | B   | B# | C#  | Cx | D# |
| Eb | Eb | Fb  | F  | Gb  | G  | Ab  | A  | Bb | Cb  | C  | Db  | D  | Eb |
| E  | E  | F   | F# | G   | G# | A   | A# | B  | C   | C# | D   | D# | E  |
| Fb | Fb | Gbb | Gb | Abb | Ab | Bbb | Bb | Cb | Dbb | Db | Ebb | Eb | Fb |
| E# | E# | F#  | Fx | G#  | Gx | A#  | Ax | B# | C#  | Cx | D#  | Dx | E# |
| F  | F  | Gb  | G  | Ab  | A  | Bb  | B  | C  | Db  | D  | Eb  | E  | F  |
| F# | F# | G   | G# | A   | A# | B   | B# | C# | D   | D# | E   | E# | F# |
| Gb | Gb | Abb | Ab | Bbb | Bb | Cb  | C  | Db | Ebb | Eb | Fb  | F  | Gb |
| G  | G  | Ab  | A  | Bb  | B  | C   | C# | D  | Eb  | E  | F   | F# | G  |
| G# | G# | A   | A# | B   | B# | C#  | Cx | D# | E   | E# | F#  | Fx | G# |
| Ab | Ab | Bbb | Bb | Cb  | C  | Db  | D  | Eb | Fb  | F  | Gb  | G  | Ab |
| A  | A  | Bb  | B  | C   | C# | D   | D# | E  | F   | F# | G   | G# | A  |
| A# | A# | B   | B# | C#  | Cx | D#  | Dx | E# | F#  | Fx | G#  | Gx | A# |
| Bb | Bb | Cb  | C  | Db  | D  | Eb  | E  | F  | Gb  | G  | Ab  | A  | Bb |
| B  | B  | C   | C# | D   | D# | E   | E# | F# | G   | G# | A   | A# | B  |
| Cb | Cb | Dbb | Db | Ebb | Eb | Fb  | F  | Gb | Abb | Ab | Bbb | Bb | Cb |
| B# | B# | C#  | Cx | D#  | Dx | E#  | Ex | Fx | G#  | Gx | A#  | Ax | B# |

Here is the same data, but transformed so that columns represent fixed notes (like "C") rather than intervals from the key's root:

**Comment by wildmatsu** [comment]
To follow up on an earlier question, I asked some friends for suggestions on how to represent a double flat, and the best solution that anyone came up with was a capital B.

**Comment by rerrahkr** [comment]
Thank you! I don't know about modes, but I understand everything else. The relationship between the fifth degree circle and chosen note names is very interesting.
If I know the theory, I can use it not only for coding but also for composing music, so I will try studying it again from the beginning.

> I asked some friends for suggestions on how to represent a double flat, and the best solution that anyone came up with was a capital B.

If you arrange 2 flats vertically, it looks like a "B". I was going to discuss it with you, but it seems that I can adopt it without that need.

**Comment by rerrahkr** [comment]
One more question, I tentatively call this feature as "Key scale", but is there a more suitable name?

**Comment by OPNA2608** [comment]
I want to mention something that might complicate the translation for these alternate note spellings: Not all regions use CDEFGAB.

In my language & country (German, Germany) as well as some other Eastern European regions, we use CDEFGA**H**. That means:

| CDEFGAB | CDEFGAH |
| :-: | :-: |
| B | H |
| B♭ | B |
| B♭♭ | ???¹ |

Since we already have a Polish translation now (which also uses this system, but at the time of writing has a mistranslation and incorrectly uses CDEFGAB), this notation anomaly should be properly handled in an implementation of this feature.

¹ I sadly don't know how `B♭♭` works in our system, my musical education wasn't in-depth enough to cover such a notation. `B♭` perhaps? :man_shrugging:

**Comment by wildmatsu** [comment]
I mentioned this in the Discord, but for convenience:

https://german.stackexchange.com/questions/26839/how-do-you-phonetically-pronounce-all-of-the-german-note-names#:~:text=The%20German%20sequence%20of%20the,the%20English%20B%20is%20H.

Therefore:

| English | German |
|---------|--------|
| B𝄫     | H𝄫    |
| B♭      | B      |
| B       | H      |
| B♯      | H♯     |
| B𝄪     | H𝄪    |
| A𝄫     | A𝄫    |
| A♭      | A♭     |
| A       | A      |
| A♯      | A♯     |
| A𝄪     | A𝄪    |

**Comment by wildmatsu** [comment]
> One more question, I tentatively call this feature as "Key scale", but is there a more suitable name?

I missed this one earlier.

I don't think any other tracker has ever implemented a feature like this to my knowledge, so I don't think there is a name for it yet. It serves a _similar_ function to what a key signature does in sheet music, but it's not quite the same thing as a key signature, either.

**Comment by rerrahkr** [comment]
I added "Key signature" settings at 037ea62a0673a6f1294e3581cca47df6b1fe1759. You can also switch the notation system between English and German.
