### ISSUE TITLE
[Feature] - Multitrack per-channel export

### ISSUE THREAD

**Issue by Toonlink8101** [BambooTracker/BambooTracker#365]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

This feature would allow the user to export multiple Wav files at once, each containing the audio for the respective channel and one containing a mix of them all. This has already been done with Dn-Famitracker, where checking a box enables this feature. This feature would be helpful both for producing oscilloscope videos as well as audio mixing and post-effects, such as reverb.

**Comment by rerrahkr** [comment]
Thanks for your request. As for the ability to export by channel, I understand its usefulness, but I don't know if it's possible with the audio emulation method.
I am using the mixed audio generated by the OPNA emulator. It may be possible to modify the emulation code to output it by channel, but I haven't checked their sources in detail yet.
This is also related to #79.

**Comment by rerrahkr** [comment]
It will take some time to export, but I think it is possible.

**Comment by Toonlink8101** [comment]
Sorry for the delayed response.

Something else I forgot to mention was extended channel 3. If this is enabled, it might be best to just export it at once, with all operators unmuted. At least for the time being, it would make sense for the exporting of the individual operators to be done manually.

Even if you decide against implementing all of this, I greatly appreciate your consideration :)

**Comment by rerrahkr** [comment]
I added this feature at 59da2595cbb29f7f2a3979b5d33449844395c0c9.
