### ISSUE TITLE
Changing tempo with Fxx effect slows down song every time you use it

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#376]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Every time you use Fxx to change a song's tempo mid-song, it resets the "partial" progress into the current row. So placing a Fxx on every row effectively rounds the song down to the next slower speed.

(Oxx groove effects do not cause a delay.)

## How to reproduce

1. Create an empty document, and add regularly spaced notes to act as a metronome.
2. Either place a single Fxx effect at the top with xx >= 20, or place Fxx effects on every row with the same xx value.
3. Compare their tempos.

For example, F80 (128 bpm) is just slightly slower than speed 7 (128.57 bpm), but if you spam F80 every row, you get speed 8 instead (112.5 bpm). The effect is more dramatic at higher tempos; for example, my example module uses FFF, which has a clearly audible change in tempo when spamming Fxx.

Example module: [bambootracker fxx tempo bug.btm.zip](https://github.com/rerrahkr/BambooTracker/files/6684020/bambootracker.fxx.tempo.bug.btm.zip)

![Screenshot_20210620_212121](https://user-images.githubusercontent.com/913957/122706771-7ab4a900-d20d-11eb-951b-a9a9be033e1d.png)

## System Information

- **Operating System**: Arch Linux
- **BambooTracker Version**: unstable-0142df4c01401c5ea525b68e9568fd3fd4063392
- **Build Type**: AUR build from source

**Comment by rerrahkr** [comment]
Thanks for your report. In BT, the step size is dynamically changed according to the tempo. In this case, the tempo is reset in each row, so the step size is not dynamically changed.
I will try not to reset the tempo if it is set the same as the previously set one.

**Comment by nyanpasu64** [comment]
If you ignore Fxx effects which don't change the tempo, it won't fix the real-world problem: using a Fxx effect on every row to simulate a tempo slide (ritardando/accelerando) will still result in the playback rate being rounded to the next slowest integer speed, instead of the fractional speeds achievable with a tempo.

**Comment by rerrahkr** [comment]
I know, but at the moment it's hard to think of a solution that would essentially solve that problem.

Many MML drivers for YM2608 use built-in timers to set the playback speed more precisely. In these drivers, the number of ticks in a whole note is fixed. It's too late now, but BambooTracker should have had such a playback system.

**Comment by rerrahkr** [comment]
> not to reset the tempo if it is set the same as the previously set one.

For now, I fixed it in 2ac8e4c9129c732d2b5d58411ea3c91970308e24
