### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Large ADPCM .bti instruments can't be loaded

### ISSUE THREAD

**Issue by freq-mod** [BambooTracker/BambooTracker#377]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

[ramune.bti.zip](https://github.com/BambooTracker/BambooTracker/files/6711143/ramune.bti.zip) - this archive contains the .bti instrument with the quite large ADPCM sample **that's smaller than 256 kB RAM limit**. However, while creating and saving was possible, loading isn't, displaying the following error:
![image](https://user-images.githubusercontent.com/32672779/123309172-e015dc00-d524-11eb-9f7c-2e56bc15de21.png)

(instrument couldn't be loaded, it's most likely corrupted, stopped at 38496)

At the same time opening a module file with such a large ADPCM instrument goes fine, no corruption, ADPCM is intact, etc..

## How to reproduce

1. Create a large wave file (for example, 1 minute long 8 KHz 16-bit PCM stream)
2. Import it as an ADPCM
3. Save the resulting instrument
4. After restarting the program, try to load it

**Comment by rerrahkr** [comment]
I made the stupid mistake, using `uint16_t` instead of `uint32_t` to read the sample size. I just fixed it in f33b82ab7db2fe22535fa8368d8b98c313b7076a. Thanks for your report!

**Comment by freq-mod** [comment]
It loads now, thanks!
