### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Unable to load the certain .PZI bank

### ISSUE THREAD

**Issue by freq-mod** [BambooTracker/BambooTracker#379]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [ ] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Very similiar problem to #308 - [PIANO.PZI.zip](https://github.com/BambooTracker/BambooTracker/files/6734719/PIANO.PZI.zip) is the file in question, refusing to load with error message claiming it may be corrupted. Likely it is because of https://github.com/OPNA2608/libopenpmd/issues/4 - magic number is PZI0, rather than PZI1.

**Comment by OPNA2608** [comment]
I've tried overwriting the magic number with PZI1 and it seems to import correctly. Similarly to #308, that's good enough for our usage of such banks.
