### ISSUE TITLE
[Windows] - WAV Export fails, export progress dialog box reappears after export and eventually results in a st:bad_alloc error

### ISSUE THREAD

**Issue by Drillimation** [BambooTracker/BambooTracker#384]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When attempting to export a module as a WAV audio file, the export progress box reappears even after it disappears and repeats until an error occurs.

## How to reproduce

1. Open any BTM file.
2. Export the file as a WAV.
3. …

## System Information

- **Operating System**: Windows 10
- **BambooTracker Version**: 0.4.6
- **Build Type**:

**Comment by Drillimation** [comment]
File where the error is occurring:
https://drive.google.com/file/d/1j1Syu_Qdu2BM08lIspV3eIDE3Ag5G9-v/view?usp=sharing

**Comment by OPNA2608** [comment]
I can't seem to reproduce this error with the linked module on Linux: Neither with a native build of 0.4.6 / master, nor with the 32-bit Windows build of 0.4.6 / master running under Wine. Can you give any more details about this, maybe a screen recording?

https://user-images.githubusercontent.com/23431373/124891427-4432a880-dfd9-11eb-8284-1a5dc7faf857.mp4

**Comment by rerrahkr** [comment]
Export dialog is buggy in v0.4.6, so I fixed it by the latest commit. Could you test the module in the current master builds from Appveyor?

**Comment by rerrahkr** [comment]
Since nothing has been reported, I assume it has been resolved.
