### ISSUE TITLE
Fixed arps not working correctly

### ISSUE THREAD

**Issue by djmaximum17** [BambooTracker/BambooTracker#386]
don't know how to explain this, is acting as if I put a loop point when clearly there isn't one. video might explain it better.

https://user-images.githubusercontent.com/61179162/125148526-88689a80-e0f8-11eb-9db0-f82beebf58b5.mov

**Comment by rerrahkr** [comment]
That is the intended behavior of BT; it keeps the value of the last sequence.
The downside of this feature, as you have shown, is that it is not possible to run a fixed pitch at the beginning of a sequence and then return to normal pitch. I know this is a common technique used in PSG to have drums and bass coexist on one channel, but unfortunately BT does not support it.

**Comment by rerrahkr** [comment]
I closed this issue but at 0869be2ed71278181a3ab94f9b861f999fca9f1d I changed the behaviour to be the same as FamiTracker. Previously created data automatically corrects the sequence when the file is loaded to ensure compatibility.
