### ISSUE TITLE
[Feature] - Adding .btm file type and association on Linux?

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#387]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

https://aur.archlinux.org/packages/bambootracker-git/#comment-816368

Is it practical to add a new MIME type for .btm files, associated with BambooTracker by default?

> this sounds like an upstream issue rather than packaging. The source should provide a xdg mimetype description along with a desktop file update to match.

Currently, BambooTracker ships a .desktop file (https://github.com/BambooTracker/BambooTracker/blob/master/data/applications/BambooTracker.desktop) but not a MIME .xml file. Is it possible to add a MIME .xml file, edit the .desktop file to add a `MimeType` key including the new MIME type, and automatically install the XML file upon `make install` (so it will get picked up by AUR packaging)?

**Comment by OPNA2608** [comment]
I'll look into it.
