### ISSUE TITLE
[Windows|macOS|Linux|BSD] - BambooTracker keeps using the speed value in Song Settings to check the validity of an effect parameter instead of the length of the current row when using grooves/tempo.

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#399]
> #### Checklist 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When I tried to make triplets in a song using the Gxx command, it initially did not work because the speed value set in Song Settings was equal to the value I used in the Gxx commands. However, when I increased the speed value, the triplets worked as expected. This is odd because I was using grooves to set the speed of the song, meaning the tracker should have used the speed of the row I was using the effect on. I suspect that this is also the case when using tempo in tandem with speed.

## How to reproduce

1. Create a new module and a new instrument
2. Set the speed to 1
3. Create a groove (e.g. "3 4 4 4" for a tempo of 120)
4. Put a note with a Gxx effect with a value of 2 or 3 on a row.
5. Play it.
6. Repeat steps 3-5 with a speed of 9.

## System Information

- **Operating System**: MacOS Mojave 10.14.16
- **BambooTracker Version**: v0.5.0
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thanks for your report. I fixed it in 73b831068c2e31063d06eb519b4dafcb7d330b3b.

**Comment by Zexxerd** [comment]
fixed
