### ISSUE TITLE
Windows - Volume Box Aesthetics

### ISSUE THREAD

**Issue by wildmatsu** [BambooTracker/BambooTracker#401]
> #### Checklist
> 
> - [ ] I am reporting exactly 1 bug with this issue. (Sorry, it is two, albeit related issues.)
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

The volume spin box at the top of the UI is too narrow, and cannot accommodate the entirety of the text it contains. I suggest making it wider. If the Volume and Octave spinboxes are made the same width as with the Step Highlight spinboxes to the right, that should  be wide enough, and it'll look nice to have them all be the same size.

Also, I suggest that capital letters be used rather than lowercase for hexadecimal digits in the volume spinbox. Capital letters for hexadecimal is more aesthetic, as the letters will all be the same size as the numbers, and more legible, as capital letters tend to be larger, simpler shapes than lowercase.

![image](https://user-images.githubusercontent.com/38014709/128903894-603fa741-e26c-4eb1-b559-a09da233b3a0.png)

## How to reproduce

Simply launch the Windows 10 release of BambooTracker. I do not know if the issue affects other releases.

## System Information

- **Operating System**: Windows 10
- **BambooTracker Version**: 0.50
- **Build Type**: Official

**Comment by OPNA2608** [comment]
Qt6 builds (like the Win10 x64 one) are barely tested and experience known UI differences/problems compared to Qt5 ones (Win7 x86, WinXP x86). This seems like one of those Qt6-specific differences (unless you can replicate this with any of the other Windows builds) so I've marked it as such for bug tracking & reproducing reasons.

**Comment by rerrahkr** [comment]
In b91e658d7ba85c1c696ee065f043c9b9ad37149f, I fixed the value to be displayed in uppercase. I also removed the maximum width settings for the spinbox.

**Comment by wildmatsu** [comment]
I can confirm the volume spinbox appears to display in uppercase. Thanks! I'll confirm the other change as soon as I can successfully build the latest dev version on my own machine.

**Comment by wildmatsu** [comment]
The Windows 10 Build now looks like this.

![image](https://user-images.githubusercontent.com/38014709/129062432-be8cac78-3af6-456a-a05f-9b08484ae8f5.png)

It is significantly improved, but a few volume values such as 7A and 7C, a few pixels of the right edge of the second digit are cut off. Ideally, I'd like this spinbox to be big enough to accommodate any value without cutoff, but it's an extremely minor issue, so if you want to call this issue fixed at this point and close the issue, I won't object. It's up to you. Thanks for fixing this issue so promptly.

**Comment by rerrahkr** [comment]
I changed the minimum width of spinboxes at b98776a178d32fd1f38d35ae65d55d146d6fce04.
