### ISSUE TITLE
Scaling artifacts on icons with Japanese locale

### ISSUE THREAD

**Issue by OPNA2608** [BambooTracker/BambooTracker#402]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When using a Japanese locale, the Qt6 builds will use a different font than Qt5 ones. This different font is slightly larger than what the UI was designed for, leading to slightly upscaled icons with upscaling artifacts (called "oozing" in https://github.com/BambooTracker/BambooTracker/pull/373#issuecomment-862311587)

Some thoughts from the server about this:

> The system font of Japanese Windows has been changed in xp, 7 and 10, so it may be affected by that
> It seems that Qt used "MS UI ゴシック" before, but now it uses "Yu Gothic UI" or "Segoe UI"

> maybe SVG icons could be used to make icon scaling look consistent at every font size instead?
> though it'd be more of a workaround than a fix i guess

## How to reproduce

1. Download / Build a Qt6 build on a Windows system with a Japanese locale
2. Run the downloaded / built binary
3. Observe the "oozing"

Comparisons (Qt5 x86 vs Qt6 x64 builds):
![grafik](https://user-images.githubusercontent.com/23431373/122212222-e1e9fa80-cea7-11eb-93fa-e58cfbbfcb18.png)
![grafik](https://user-images.githubusercontent.com/23431373/122212258-eb736280-cea7-11eb-9ea5-0c695697695a.png)
![grafik](https://cdn.discordapp.com/attachments/769177992471511126/854343260013199381/pic.png)

## System Information

- **Operating System**: Windows 10
- **BambooTracker Version**: v0.5.0
- **Build Type**: Official (Win10 x64 - Qt6)

**Comment by OPNA2608** [comment]
@rerrahkr can you check if #407 solved this for you? The fonts in use should still be different, but the icons might look fine now.

**Comment by rerrahkr** [comment]
It works fine! Thank you!
