### ISSUE TITLE
Windows|??? - Qt 6 builds incorrectly map mouse position to pattern/order rows

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#406]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

In the Qt 6 builds, when hovering rows above the center of the pattern/order editors, the tracker highlights one row above the mouse cursor (even without DPI scaling).

## How to reproduce

1. Download BambooTracker "Windows 10 64-bit" (Qt 6 based) and open a demo module. (The bug does not occur in Qt 5 builds.)
2. Scroll down in the order list and pattern editor.
3. Hover rows above the cursor in the order list (wrong highlight), rows above the cursor in the pattern editor (wrong highlight), and rows in previous patterns (correct highlight).

## System Information

- **Operating System**: Windows 10
- **BambooTracker Version**: 0.5.0 and master a777b4f2d69a52458efbe1c3c13bf38a4e26214b
- **Build Type**: Official and self-built

**Comment by rerrahkr** [comment]
Thank you for your report. Qt6 uses `QPointF position()` to get the cursor position for mouse hover events, but there was a problem with the implicit type conversion from double to int. I fixed it in d236c97d0d4eed6ed379e3e6e59872ba793946cd.

**Comment by nyanpasu64** [comment]
qCeil() and qFloor() may be more concise because it automatically casts the result to int. Is the codepath you edited Qt6-specific or Qt5 as well?

**Comment by rerrahkr** [comment]
It is common in Qt 5 and 6.
