### ISSUE TITLE
[Windows|macOS|Linux|BSD] - using ESxx doesn't reset the release rate of an instrument, affecting key-offs and the 0Sxx effect.

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#413]
> #### Checklist
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

It appears that the effect of setting the envelope's release rate to 15 doesn't reset directly after using ESxx on a channel. This makes the instrument (in that usage context) cut instantly when one uses again on the same channel and then uses 0Sxx or a key-off. This stops occurring when one switches to another instrument in the same context.
To fix this, the release rate should be restored on the next tick or as soon as possible.
## How to reproduce

1. Create an instrument.
2. Have it play a sequence that tests key-off and/or 0Sxx before and after using ESxx.
3. Notice the difference.

## System Information

- **Operating System**: macOS Mojave v10.14.6
- **BambooTracker Version**: v0.5.0
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thank you for your report. I fixed it in a468ee62f6388f8a2928d2bf52d8b6a7e026acd5.
