### ISSUE TITLE
[Feature] - SPB ("SpeakBoard"?) sample support

### ISSUE THREAD

**Issue by OPNA2608** [BambooTracker/BambooTracker#414]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

Support for importing (and maybe exporting too?) .SPB files. Supposedly has no header, just consists of a single sample in ADPCM-B format.

[examples.zip](https://github.com/BambooTracker/BambooTracker/files/7130976/examples.zip)

**Comment by rerrahkr** [comment]
Thank you for your info and a sample. It seems easy to add, so I'll give it a try.

**Comment by rerrahkr** [comment]
I added a feature supporting .spb import as ADPCM sample at 95d6e6ea71fbe2402689b2e90fc9be6644e392f5.
Note BT sets a root key to C5,16kHz automatically since it can get only 1 raw sample from a file.
