### ISSUE TITLE
Linux - Calling BambooTracker with relative path saves relative path into recent files

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#417]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

If I call `BambooTracker file.btm` on the command line, it saves "file.btm" in the recent files list without resolving the path. If you relaunch BambooTracker in a different working directory, trying to open this recent file fails because it looks in the new working directory.

## How to reproduce

1. Open a terminal to a directory with .btm files.
2. `BambooTracker file.btm`
3. View the File menu -> Recent Files.

## System Information

- **Operating System**: Arch Linux
- **BambooTracker Version**: unstable-06e20993
- **Build Type**: AUR bambootracker-git

**Comment by rerrahkr** [comment]
Thank you for your report. I fixed it in b163361c912571777686bc9288deadf49c5f02e3.
