### ISSUE TITLE
0Sxx/0Gxx with xx = speed - 1 is erased by next-row 0Gxx on earlier channel

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#421]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

If I use a 0Sxx/0Gxx effect to delay a row by the current speed minus 1, then the next row (on the same or next pattern) has a 0Gxx (not 0Sxx) command in an earlier channel, the first row's 0Sxx/0Gxx doesn't take effect.

## How to reproduce

1. Download, extract, and open [gxx dropped bug.zip](https://github.com/BambooTracker/BambooTracker/files/7175373/gxx.dropped.bug.zip). This file has a speed of 9, and G08 and S08 effects.
2. Play the song. Because FM2 has 0G01 effects (0G00 doesn't cause the bug), FM3 and FM4 (but not FM1)'s 0G08 and 0S08 effects don't take effect.

![Screenshot_20210915_233404](https://user-images.githubusercontent.com/913957/133561827-653eb2fa-ea10-4703-9a0f-7e759ab959dd.png)

## System Information

- **Operating System**: Arch Linux
- **BambooTracker Version**: unstable 06e209936597fd6663d51bea2594c4548de669b0
- **Build Type**: AUR bambootracker-git

**Comment by rerrahkr** [comment]
Thank you for your report. I fixed it in 648f69193a25841c99d5931c14c7fdaa014d09bb.
