### ISSUE TITLE
Linux - Out-of-bounds crash when deleting 0Dxx, scrolling down, and undoing

### ISSUE THREAD

**Issue by nyanpasu64** [BambooTracker/BambooTracker#422]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [ ] This bug hasn't already been reported???
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

If you delete a 0Bxx/0Cxx/0Dxx effect, scroll past its position, and undo, you get a `vector::_M_range_check: __n (which is "Pattern size") >= this->size() (which is "Pattern size")` error, and the pattern editor stops rendering until you close and reopen the program.

Alternatively your cursor ends up in rows past a pattern-truncating effect that shouldn't be visible, and moving the cursor causes the rows to disappear.

## How to reproduce

1. Open a document with a 0Dxx (or 0Cxx/0Dxx) effect (these effects truncate patterns), for example a file in [dxx oob bug.zip](https://github.com/BambooTracker/BambooTracker/files/7175623/dxx.oob.bug.zip). Delete the 0Dxx effect.
2. If the effect was on the last row of the pattern, increase the global "Pattern size".
3. Scroll to a row past where the 0Dxx effect used to be, and undo deleting it.

## Results

If the window height is small enough (relative to the current pattern size) for all on-screen rows to be in-bounds (less than the size of the current pattern), your cursor remains in place, in rows that should be hidden because of the 0Dxx effect. Moving the cursor will hide these rows and clamp your cursor back in-bounds.

If your window is tall enough to show rows past the current pattern size, you get an uncaught exception and popup, with the following stack trace (by commenting out the try-catch in `QApplicationWrapper::notify` and `main`):

```
std::__throw_out_of_range_fmt(const char *, ...) (.cold)
std::vector<Step>::_M_range_check(unsigned long) const
std::vector<Step>::at(unsigned long)
Pattern::getStep(int)
BambooTracker::getStepNoteNumber(int, int, int, int) const
PatternEditorPanel::drawStep(QPainter&, QPainter&, QPainter&, int, int, int, int, int, int)
PatternEditorPanel::drawRows(int)
PatternEditorPanel::drawPattern(QRect const&)
PatternEditorPanel::paintEvent(QPaintEvent *)
QWidget::event(QEvent *)
PatternEditorPanel::event(QEvent *)
```

This results from a loop over the current pattern (with length "Pattern size") failing to terminate and indexing out of bounds:

https://github.com/BambooTracker/BambooTracker/blob/06e209936597fd6663d51bea2594c4548de669b0/BambooTracker/gui/pattern_editor/pattern_editor_panel.cpp#L683-L686

I think `curPos_.step` is the cursor row, `stepNum` is the row being drawn, and the loop never ends because `stepNum > stepEnd` (the cursor is past the end of the pattern because it wasn't clamped properly when undoing "delete 0Dxx"). In this case, the cursor is in-bounds relative to "Pattern size", but out-of-bounds relative to 0Dxx.

Maybe the solution is to clamp the cursor position when undoing "delete 0Dxx", maybe it's to defensively check for `if (stepNum >= stepEnd)`, maybe add extra assertions to catch the invariant of "the cursor is in-bounds" being broken, instead of having to deduce it from the side effects.

## System Information

- **Operating System**: Arch Linux
- **BambooTracker Version**: unstable 06e209936597fd6663d51bea2594c4548de669b0
- **Build Type**: AUR bambootracker-git, and Qt Creator

**Comment by rerrahkr** [comment]
Thank you for your report. I'll try to clamp the cursor position when redo/undoing commands related to effect entry.

**Comment by rerrahkr** [comment]
I modified the cursor position check in the pattern editor which runs before repainting at 6efaa093ebcf217ad6c7cf1daceb1329c50e2fc0. It works fine as far as I checked.
