### ISSUE TITLE
Weird macro behavior when using Gxx

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#425]
> #### Checklist
>  
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [?] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
<img width="247" alt="Screen Shot 2021-10-25 at 2 15 49 AM" src="https://user-images.githubusercontent.com/48669774/138643800-64d60bf9-7cf6-42da-bbb7-1ad0e59e9987.png">
This was only tested on the SSG channels. Instrument 00 uses an envelope macro that imitates a xylophone.
The first note on the first channel plays as normal, but due to the Gxx effect, the other notes never play properly, potentially because macro execution starts before the note plays, making the note play xx ticks into the macro.

## How to reproduce

1. Create an envelope macro for an instrument
2. Play the instrument by pressing "Play" to play the song.
3. Do the same thing, but put a Gxx effect by it, with xx being greater than 0.

## System Information

- **Operating System**: MacOS Mojave
- **BambooTracker Version**: v0.5.0
- **Build Type**: Official

**Comment by rerrahkr** [comment]
I apologize for not responding to your report for so long.

[decay_and_delay.zip](https://github.com/BambooTracker/BambooTracker/files/8716212/decay_and_delay.zip) - I tried to reproduce it with this file but could not with the current master. If possible, would you mind checking if it still happens in your environment?

**Comment by Zexxerd** [comment]
Yes, it does still happen in my current environment. For the first row, try deleting all of the Gxx effects and compare the two outputs.

**Comment by rerrahkr** [comment]
Ah, I see that the envelope is not working well in my environment either. I'll take a closer look.

**Comment by rerrahkr** [comment]
There were a bug that caused sequence properties such as envelope sequence to skip the first data when note on was triggered by `0Gxx`. I fixed it at b4347f397f8877a8461e3136c872d8ee8ab9b8f5.

**Comment by Zexxerd** [comment]
fixed.
