### ISSUE TITLE
[All] - VOPM textual instrument label breaks parsing

### ISSUE THREAD

**Issue by OPNA2608** [BambooTracker/BambooTracker#430]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Textual instrument labels in a VOPM file break the file parsing.

## How to reproduce

1. Try to import this VOPM patch:
```
@:No
LFO: 0 0 0 0 0
CH: 64 6 4 0 0 120 0
M1: 30 0 4 3 0 24 0 3 3 0 0
C1: 23 12 31 3 3 19 0 6 0 0 0
M2: 23 12 31 3 3 127 0 8 0 0 0
C2: 23 12 31 3 3 17 0 4 2 0 0
```

2. Observe this error:
![Bildschirmfoto_2021-11-09_19-02-25](https://user-images.githubusercontent.com/23431373/140979293-94d44605-d7d7-4171-98d6-b6420de123da.png)

3. Change the `@:No` to `@:0`
4. Now it works.

## System Information

- **Operating System**: NixOS 21.05 (Okapi) x86_64 & Windows (presumably, not my system)
- **BambooTracker Version**: v0.5.0
- **Build Type**: Package Manager

**Comment by rerrahkr** [comment]
I apologize for not responding to your report for so long.
VOPM envelope loading feature assumes that you copy and paste the text from an .opm file.
.opm file contains numerical values representing instrument numbers in the "No" location, and the text parsing is based on this assumption, so this behavior is in accordance with the specification.
