### ISSUE TITLE
Create a "note cut" effect distinct from existing "note release"

### ISSUE THREAD

**Issue by wildmatsu** [BambooTracker/BambooTracker#433]
> #### Checklist
> 
> - [x] I am requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

My understanding is that one of the design goals of BambooTracker is to work like Famitracker. In recent forks of Famitracker (0CC-Famitracker and other forks based on it, including DN-Famitracker), a note cut instantly silences the channel, and note release plays the note's release pattern.

BambooTracker offers a way to release notes, but no way to cut them. I think note cut would be a worthwhile effect to add. It would also be ideal to implement it similar to how Famitracker does, to make it easier for FT users to pick up BT. Therefore, let me quickly summarize how FT does it.

![image](https://user-images.githubusercontent.com/38014709/143778343-d7e4947e-f77a-4699-8d4c-b8f42e480113.png)

A horizontal line, as seen in Pulse 1 row 02, is a note cut. A double horizontal line, as seen in Pulse 2 row 02, is a note release. Sxx is a delayed note cut that occurs xx ticks after the row. Lxx is, similarly, a delayed note release.

Unfortunately, the way the note release effect works in BambooTracker right now is inconsistent with Famitracker. The note release uses the horizontal line and the 0Sxx effect, which is what Famitracker uses for note cut. BT cannot be made consistent with Famitracker without breaking compatibility with older modules and/or confusing users.

Additionally, the 0Sxx effect, which behaves as a release effect, is incorrectly described in documentation and the program itself as a "note cut" instead of a note release. I will create a separate issue for this.

One suggestion for how to address this would be to leave the 0Sxx effect's behavior alone but mark it as deprecated. Then, introduce SSxx for note cut and LLxx for note release. I have no suggestion for how to deal with the horizontal line/double horizontal line issue, though.

**Comment by wildmatsu** [comment]
Relevant discussion about this issue from the Discord:

```
Perkka:
saw the issue you opened, though about the line vs double line... that could simply be changed since it's only a visual thing
and shortcut could be changed
it would not break anything in the existing files

Wild Matsu:
hmm
i think that still could potentially confuse users
but it might be the best way to handle it

Perkka:
well if they open an old module all note releases would now asspear as === instead of ---
and that would maybe make people double check the release notes to see what's changed
release notes as in release version documentation/version history 

Wild Matsu:
the potential pitfall of that is that someone will download the hypothetical new version of bambootracker which changes what the horizontal line means
and then create a new module from scratch
and be confused why the behavior of --- has suddenly changed
or not notice it

Perkka:
yea
that's the biggest issue i suppose
```

**Comment by rerrahkr** [comment]
Sorry, I also thought of implementing it later, but have not been able to do so due to compatibility difficulties with existing functions and names. Currently the only solution is to turn off the volume (for FM, you can use `ESxx` to "note cut" in the original sense).

Note cut" is an effect that has been included since v0.1, and at that time I did not yet emphasize compatibility with FamiTracker as a design concept for the tracker.
At the beginning of the development, I thought it was impossible to turn off the sound immediately in FM due to the existence of the RR parameter (but it is possible in fact). So, I decided to unify the note-off process by having "note release" in FT be "note cut" in BT, which resulted in this confusion.

**Comment by rerrahkr** [comment]
I plan taht the name of `0Sxy` will be changed to "Note Release" in the next version. Also, since `ESxy` Envelope Reset in FM has the same effect as "Note Cut", the name of this effect will be changed and I'll make it work with SSG and ADPCM as well .

**Comment by wildmatsu** [comment]
That sounds like an excellent solution.

**Comment by rerrahkr** [comment]
After ec9e09d7be7a9fa2f4b3871aaa0f60055cf10ef0, you can use "note cut" and "not release" effects (documents are also modified #434).
I also added "key cut" as note event, which is the same as a note cut effect, and changed sign of "Key off" (Note release) to match the appearance of FamiTracker.

| | Key off (Key release) | Key cut |
|---|---|---|
| &le;v0.5.3 |![Previous key off sign](https://user-images.githubusercontent.com/26477882/207862118-5ae388a5-dfe2-4dc9-840c-e0e755bc7ed4.png)||
|After ec9e09d7be7a9fa2f4b3871aaa0f60055cf10ef0 |![New key off sign](https://user-images.githubusercontent.com/26477882/207862292-29f3cee2-f52d-4b4f-98ab-6ef247cf6244.png)|![New key cut sign](https://user-images.githubusercontent.com/26477882/207862118-5ae388a5-dfe2-4dc9-840c-e0e755bc7ed4.png)|

The default shortcut does not assign any keys to key cut, so change the configuration if you want to use it.
