### ISSUE TITLE
0Sxx effect incorrectly labeled "note cut"

### ISSUE THREAD

**Issue by wildmatsu** [BambooTracker/BambooTracker#434]
> #### Checklist
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

The documentation and program itself describe 0Sxx as a note cut effect (which would instantly silence the channel). Its behavior is actually that of a note release, which either plays the FM patch's release behavior, or advances the SSG channel to the defined release envelope.

This issue is related to this larger issue: https://github.com/BambooTracker/BambooTracker/issues/433

## How to reproduce

1. Open the Effect List:

![image](https://user-images.githubusercontent.com/38014709/143778716-81602ca4-0ddc-4a9f-bb5b-33ac15289160.png)

2. Or, input an 0Sxx effect and look at the text at the bottom left:

![image](https://user-images.githubusercontent.com/38014709/143778744-8e3dd57a-a6c6-4e2d-88e1-d0e6abc9367c.png)

3. The description is also incorrect on the wiki.

## System Information

- **Operating System**: Windows 10
- **BambooTracker Version**: 0.5
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Fixed in #433
