### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Envelope generator remains audible even when SSG channel is muted.

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#437]
> #### Checklist
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When you use the 0H/0I/0Jxx effects to use the envelope generator on the SSG channels, the envelope generator remains audible if you mute the channels you are using it on, making it the only thing audible when all channels are muted. This problem even carries over into WAV export, when you export by channel the envelope generator is audible in each channel file. 

## How to reproduce

1. Use these parameters ("0H0C, 0I00, 0J80", just an example) on an SSG channel.
2. Play with the SSG channel unmuted.
3. Stop playback and play with the SSG channel muted.

## System Information

- **Operating System**: MacOS Mojave (v10.14.6)
- **BambooTracker Version**: v0.5.0
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thank you for your report. I fixed it at c0fe0c2527f0511cb39e0bb130ebbeea24fd8173.

**Comment by Zexxerd** [comment]
fixed
