### ISSUE TITLE
[Windows] - Estimate Song Length displaying incorrect time on some modules

### ISSUE THREAD

**Issue by Drillimation** [BambooTracker/BambooTracker#443]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
When attempting to use the estimated song length to check the length of a song, the time will display incorrectly. For example, one module may say the song is 50 minutes long when it is only two minutes long.

## How to reproduce

1. Open any BambooTracker module.
2. Check the song length via Estimate Song Length

## System Information

- **Operating System**: Windows 10
- **BambooTracker Version**: 0.5.0

**Comment by Drillimation** [comment]
[Mystery of the Soul.zip](https://github.com/BambooTracker/BambooTracker/files/8248835/Mystery.of.the.Soul.zip)
Here's an example module that causes the bug.

**Comment by rerrahkr** [comment]
I apologize for not responding to your report for so long. I fixed it at 469fc77e0327347760438f5f91923536073a643b.
