### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Special Ch3. Mode's 4th operator resets improperly when retriggered.

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#444]
> #### Checklist
 
> - [?] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
I know BambooTracker is basically no longer in development, but I still feel that this needs to be known.
Basically, when using the extended mode for channel 3 in v0.5.0, the 4th operator acts weird. When you trigger another note after playing one on the channel, it will suddenly drop to a lower volume or even straight up reset the envelope. In one module I have, it resets the envelope consistently even though I didn't use any note releases.

## How to reproduce

1. Create a song that uses the extended mode.
2. Create an instrument using algorithms 4, 5, 6, or 7 (Ideally 4 or 7)
3. Create a sequence that plays at least two notes that are played through the 4th operator.
4. Observe.

## System Information

- **Operating System**: macOS Mojave, Version 10.14.6
- **BambooTracker Version**: v0.5.0
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Sorry for the late reply and thank you for your report. I fixed it at 604ce4a10c272f82bf186417aaf3537158a2d89c.

**Comment by Zexxerd** [comment]
fixed
