### ISSUE TITLE
[Windows,macOS,Linux] - .ico embeds are not displaying properly

### ISSUE THREAD

**Issue by OPNA2608** [BambooTracker/BambooTracker#451]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

The BambooTracker icon on the Welcome window has disappeared at some point, not sure when.

## How to reproduce

1. Help -> Welcome…
2. See screenshots

Native, self-compiled & `make install`d:
![Bildschirmfoto von 2022-05-26 15-56-22](https://user-images.githubusercontent.com/23431373/170503291-c28c3f97-3d5b-4aac-978c-b69a9b93b344.png)

Win7 dev build, running under Wine:
![Bildschirmfoto von 2022-05-26 16-03-47](https://user-images.githubusercontent.com/23431373/170503744-9b01a3f0-e0e7-4198-b96d-20cbd0e82594.png)

## System Information

- **Operating System**: Linux
- **BambooTracker Version**: b4347f397f8877a8461e3136c872d8ee8ab9b8f5
- **Build Type**: Locally & Official Windows 7 dev build via Wine

**Comment by OPNA2608** [comment]
Icon actually displays fine on macOS. On Linux & the Windows builds (at least under Wine) it's broken.

**Comment by rerrahkr** [comment]
Thank you for your report. I notice the "About" dialog also miss the icon image.

build with Qt Creator (win11):

![qtcreator](https://user-images.githubusercontent.com/26477882/170519264-e70d7057-9d6e-48f4-9cf9-9fc7e6c2142c.png)

v0.5.0 release bin (for win10):

![release](https://user-images.githubusercontent.com/26477882/170519524-1ab50b2d-7a70-472a-bbab-e32f21829fb0.png)

I haven't looked at it in detail, but it may be failed to display .ico file.

**Comment by OPNA2608** [comment]
The icon on the About window works on both Linux & macOS, on local builds.

> build with Qt Creator (win11):

Someone checked the b4347f397f8877a8461e3136c872d8ee8ab9b8f5 dev build and the icon isn't there either. I checked the v0.5.0 & 3f595611 (random build i still had downloaded) artifacts on my macOS machine and both didn't display either icons either. But if I locally build both commits against my system Qt, the icons work.

Seems like something we're doing in the packaging is breaking .ico support. A shot in the dark: maybe removing `imageformats` from the artifacts?

**Comment by OPNA2608** [comment]
Yep, leaving `imageformats` inside the Appveyor Windows artifacts seems to fix ico support under Wine. `qico.dll` is likely the magic library :wink:.
![Bildschirmfoto von 2022-05-26 18-48-18](https://user-images.githubusercontent.com/23431373/170535497-096ed829-2d92-4716-b463-b2f84516365b.png)

The `imageformats` directory is ~ 2MB on the Win7 dev build.
![Bildschirmfoto von 2022-05-26 18-44-07](https://user-images.githubusercontent.com/23431373/170534720-fa0a8bbf-b9af-4aa8-b3ba-20eac1eeb40a.png)

Do you want to copy around this library on CI so we only ship `imageformats/qico.dll` and delete everything else, or should we leave the entirety of `imageformats` in the artifacts?

**Comment by rerrahkr** [comment]
Since it is better to keep the package size small, I would like to remove non-essential files if possible. However, I don't mind leaving everything if that seems to be difficult.
