### ISSUE TITLE
Add a Music Length to the Status Bar

### ISSUE THREAD

**Issue by amiacat** [BambooTracker/BambooTracker#456]
> #### Checklist
> 
> 
> 
> - [ ] I'm requesting exactly 1 feature with this issue.
> - [ ] This feature hasn't already been requested.
> - [ ] This feature hasn't already been implemented in the latest development build.

---

**Comment by rerrahkr** [comment]
Thank you for your request. Honestly I don't want to place too many items on the status bar because they might hide the message. I think the length of the song is only checked rarely, and can still be done with Menubar "Song" - "Estimate Song Length".

**Comment by amiacat** [comment]
> Thank you for your request. Honestly I don't want to place too many items on the status bar because they might hide the message. I think the length of the song is only checked rarely, and can still be done with Menubar "Song" - "Estimate Song Length".

hm ok then, thanks :)
