### ISSUE TITLE
Add a time viewer on status bar

### ISSUE THREAD

**Issue by amiacat** [BambooTracker/BambooTracker#457]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [ ] This feature hasn't already been requested.
> - [ ] This feature hasn't already been implemented in the latest development build.

---

**Comment by rerrahkr** [comment]
I'm sorry, but could you please suggest specifically which part of the tracker should show an overview of which features?

**Comment by amiacat** [comment]
> I'm sorry, but could you please suggest specifically which part of the tracker should show an overview of which features?

Ah yes, like, show how many seconds music have on Status Bar, like in Famitracker.

**Comment by amiacat** [comment]
> > I'm sorry, but could you please suggest specifically which part of the tracker should show an overview of which features?
> 
> Ah yes, like, show how many seconds music have on Status Bar, like in Famitracker.
