### ISSUE TITLE
[Windows|macOS|Linux|BSD] - 0Axx effect is buggy in channel 3's special mode.

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#459]
> #### Checklist 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
Using `0Axy` doesn't work on operators 2 and 3 of channel 3 in "FM3ch Extended" mode.
## How to reproduce

1. Create a song in "FM3ch Extended" mode.
2. Create an instrument using algorithm 7 (Additive).
3. Set each operator's TL value to the maximum.
4. Put a different note into each FM3ch channel, and set each volume to a quiet value (e.g. 10h).
5. Put down `0A10` beneath each note.
6. Press play and compare channels.
7. Set each note's volume to 7Fh.
8. Put down `0A01` beneath each note.
9. Repeat Step 6.

## System Information

- **Operating System**: macOS Mojave
- **BambooTracker Version**: v0.5.1
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thank you for your report. It also does not works `EAxy` well. I'll check it in detail.

**Comment by rerrahkr** [comment]
It was because the volume data was written to the wrong address, so I fixed it at c3abf4bbddeb3969de67aa543e8366439d866167.

**Comment by Zexxerd** [comment]
Fixed
