### ISSUE TITLE
[Windows] - WAV Export Dialog Box Opens Again after progress bar reaches end

### ISSUE THREAD

**Issue by Drillimation** [BambooTracker/BambooTracker#460]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When exporting a WAV version of a file, the progress dialog box reappears again after it gets to the end and starts over. 

## How to reproduce

1. Export any BTM file to WAV.

## System Information

- **Operating System**: Windows 10 21H2
- **BambooTracker Version**: v0.5.2 
- **Build Type**:

**Comment by rerrahkr** [comment]
I tried to reproduce it with BambooTracker-v0.5.2-windows-10-64bit.zip on my Windows 11, but I couldn't.
Could you tell me which zip package you used and the wav export settings (sample rate, loop count, etc.)? And if possible, please send me the module that causes the problem.

**Comment by Drillimation** [comment]
I did it at the default settings with it looping three times. I have attached a sample file in compressed in a ZIP folder.
[Dance of the Lunatic Red Eyes.zip](https://github.com/BambooTracker/BambooTracker/files/9424723/Dance.of.the.Lunatic.Red.Eyes.zip)

**Comment by rerrahkr** [comment]
Thank you, I could reproduce it.

**Comment by rerrahkr** [comment]
The song length is calculated incorrectly when the module has `0Dxx` effect at the end of song. I fixed it in 478ff73eed1aec8e3b62e82a16817efe436a77fe.
