### ISSUE TITLE
[Feature] - Implement sample Loop points on ADPCM

### ISSUE THREAD

**Issue by pedipanol** [BambooTracker/BambooTracker#465]
> #### Checklist
> 
> 
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

When ADPCM got implemented in Bambootracker I was questioning why there wasn't a loop possibility, because I'd been using PMD and it could do that. But then I looked at the ym2608 application manual and found out that there's some driver trickery going on in there instead of being a feature of the chip itself.

In writing my current guide to PMD MML, me and Altiamie looked deep into many things of the driver, including ADPCM. Looking into the source code she figured out how it works and I thought it could be a good possibility to implement in Bambootracker:

>When the tone begins (key on), PMD first triggers a reset by setting the PCM reset flag (A1$00 = $21). It then sets the earlier-calculated sample start and end addresses with registers A1$02 (start address low), A1$03 (start address high), A1$04 (stop address low), and A1$05 (stop address high).
>
>It then checks the loop addresses for the sample. If they are equal, then the sample is considered to not be looping. By default, the loop start and end addresses are 0, so this check always passes if loop offsets aren't specified in the MML. PMD sets the PCM start flag (A1$00 = $A0) to begin playback without looping.
>
>Otherwise, the loop addresses are not equal, indicating that the sample should loop. Firstly, both the PCM start and repeat flags are set (A1$00 = $B0) to begin playback with looping. Now, because playback has started, the loop offsets can be applied without causing playback to jump to the loop start early. PMD takes the earlier-calculated loop start and end addresses and sets them to the PCM start and end address registers, A1$02-$05.
>
>Finally, regarding the release behavior, upon the tone being released (key off), it checks if the release address is 0x8000, the default value which indicates no special behavior. If it is, then nothing else happens. Otherwise, the same process for preparing a non-looping sample is performed, but with the release address as the start address, and the sample's end address as the end address

Maybe replicating this kind of behavior can allow setting loop points in the ADPCM instruments in BambooTracker. Due to how the ADPCM is decoded it's difficult to make a smooth loop, but the visual aid in the ADPCM instrument screen could make that easier.

I'm certain this is a big ask, but I figured it might be worth at least bringing the possibility up.

**Comment by rerrahkr** [comment]
Thank you for your request and info!

I had never used ADPCM with PMD, so I didn't know that loop and release points could be set. But there is indeed mention of such a function in section 6-1-5 of PMDMML.MAN.
I had thought about the possibility of a partial loop by rewriting the start/end address during playback, but I had doubts about whether such control was possible on the actual chip, so I did not try it. But I was interested to hear about it...

I'm not sure about assembly, but looking at the code, is this probably the order of writing to ADPCM registers when loop and release are set?

#### Key On

1. Reset
2. Set key on position to Start Address
3. Set loop end position to Stop Address
4. Start ADPCM synthesss and set repeat flag
5. Set loop start position to Start Address

#### Key off

1. Reset
1. Set release start position to Start Address
2. Set release end (end of sample) position to Stop Address
3. Start ADPCM synthesis without repeat flag

**Comment by rerrahkr** [comment]
That was checking the busy flag, I see. I know a little more about how PMD waits, I will use this as a reference when modifying the playback routines.

**Comment by rerrahkr** [comment]
Implemented in #476. It is not possible to move the repeat point by dragging on the sample view. I considered adding this feature, but since it is experimental, I decided to add only minimal functionality.
