### ISSUE TITLE
[macOS] - OPN YM2203 - zero fluxuation in level still outputs redundant byte sequences 

### ISSUE THREAD

**Issue by bferguson3** [BambooTracker/BambooTracker#466]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [?] This bug hasn't already been fixed in the latest development build.

---

## How to reproduce

1. Create a new OPN file with instrument that adjusts total level ports ($4E, etc)
2. Export as YM2203 VGM (for PC-8801)
3. Observe the byte sequence in the resulting VGM contains a lot of redundant byte sequences: 
```
$62 $55 $4E $7F $62 $55 $4E $7F
$62 $55 $4E $7F $62 $55 $4E $7F
$62 $55 $4E $7F $62 $55 $4E $7F
$62 $55 $4E $7F ... 
```

any series of this length can be abbreviated after the first write of $7F to only "$62" (wait frame) and the resulting song would be identical. 

## System Information

- **Operating System**: 
- mac os 12.3 apple m1 silicon
- **BambooTracker Version**: 
- 0.5.1
- **Build Type**: 
official 
[88test2.vgm.zip](https://github.com/BambooTracker/BambooTracker/files/10087612/88test2.vgm.zip)
[88test.btm.zip](https://github.com/BambooTracker/BambooTracker/files/10087622/88test.btm.zip)

**Comment by rerrahkr** [comment]
Thank you for your report. `0Axy` had a bug and I fixed (#459). Would you mind check your module with the latest release? Sorry, but you will probably have to manually double the volume slide value, but vgm will be written out without any problem.
