### ISSUE TITLE
macOS - moving sliders in instrument editor moves other sliders (regression in version >0.5.0)

### ISSUE THREAD

**Issue by cxong** [BambooTracker/BambooTracker#468]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [ ] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

In the instrument editor, when moving some sliders, the other sliders move as well, at different rates, when the value gets near 0.

## How to reproduce

1. Edit an instrument
2. Drag any slider so that it approaches 0
3. The other sliders will start to move

![slider](https://user-images.githubusercontent.com/1083215/205486255-74bb0830-3965-4861-b4bc-3dd246457de3.gif)

Bug can be also seen in official release 0.5.2, 0.5.3

## System Information

- **Operating System**: macOS Ventural 13.0
- **BambooTracker Version**: v0.5.1
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thank you for your report. That is so terrible. I don't have a Mac so I can't check right away, but I'll check later to see if I changed anything before.

**Comment by rerrahkr** [comment]
Does this glitch also affect the FM instrument or is it just a user interface issue?

**Comment by cxong** [comment]
no - also if you look closer the numbers aren't changing, only the position of the sliders

**Comment by rerrahkr** [comment]
It seems a bug caused by Qt: https://bugreports.qt.io/browse/QTBUG-98093.
In #470 I try to update Qt to the latest, but build is not working well. If that does not solve the problem, I need to create a custom slider to correct the drawing.

**Comment by cxong** [comment]
Tested ^ under macOS ventura (13.0), lg2m

**Comment by rerrahkr** [comment]
Updated to Qt6 in e9c5284, it would solve this issue.
