### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Instrument operator slider go all over the place when modified

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#469]
> #### Checklist
> - [x] I am reporting exactly 1 bug with this issue.
> - [] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

I recently upgraded to MacOS Monterey, and I saw that whenever I tried to adjust the operator values, they would eventually start going all over the place. The actual values do not change.
In contrast, I saw that this glitch does not happen in v0.4.5.
## How to reproduce

1. Open an instrument
2. Change the attack value or change another slider
3. Observe the other sliders.

## System Information

- **Operating System**: macOS Monterey 12.6.1 
- **BambooTracker Version**: v0.5.3
- **Build Type**: Official

**Comment by cxong** [comment]
already reported dude https://github.com/BambooTracker/BambooTracker/issues/468

**Comment by Zexxerd** [comment]
that's crazy
