### ISSUE TITLE
[Windows] - RSS Tripping During Playback, causing noise spikes

### ISSUE THREAD

**Issue by Drillimation** [BambooTracker/BambooTracker#478]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
During playback, the RSS will sometimes trip and produce spikes in noise. The noise spikes are also present if a file is exported as a WAV.

## How to reproduce
Open any BTM file with RSS notes and play it.

## System Information

- **Operating System**: Windows 10 22H2
- **BambooTracker Version**: v0.6.0
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thank you for your report. As far as I can see the problem does not occur. is it possible to send a sequence that causes the problem?
There have been some changes in emulation since v0.6.0, so if you don't mind, could you please show us how the sound tab in the configuration is set up, e.g. with a screenshot?

**Comment by Drillimation** [comment]
![Screenshot 2023-01-23 074037](https://user-images.githubusercontent.com/48524570/214042136-252ee724-7ed4-47f1-bb22-1e2967637505.png)
![Screenshot 2023-01-23 074133](https://user-images.githubusercontent.com/48524570/214042260-41f2c78e-ede1-48d6-ae00-49163bc5196f.png)
[A Pure and Innocent Fleeting Flower.zip](https://github.com/BambooTracker/BambooTracker/files/10479757/A.Pure.and.Innocent.Fleeting.Flower.zip)

I have put down two screenshots alongside a sample .BTM file that you can export to WAV.

**Comment by rerrahkr** [comment]
I'm sorry, does "tripping" mean that there is a sound that does not sound? Or does it mean that there is noise at the attack?

A possible cause of noise is that the volume of the track is too loud, resulting in clipping. Clipped sounds do not resample well and can cause distortion. blip_buf resampling added in v0.6.0 is more affected.

**Comment by Drillimation** [comment]
I happened to find a workaround. I changed the resample to the old and outdated "linear" setup and the noise spikes happened to go away for the most part.

**Comment by rerrahkr** [comment]
Checked the video, maybe the volume clamping is missing somewhere... I'll try to make a modified test build.

**Comment by rerrahkr** [comment]
Could you also tell me how it behaves when you check "zero-wait write" checkbox in [Configuration] - [Sound]?

**Comment by Drillimation** [comment]
I'm experiencing normal behavior with it on.

**Comment by rerrahkr** [comment]
I could replicate this issue. Also, blip_buf only sounds normal at 55466Hz, the sample rate at which the FM output is passed directly to the mixer without internal resampling. Until the issue is solved, the sample rate should be set to 55466 Hz for the time being if you wish to use blip_buf.

**Comment by rerrahkr** [comment]
I modified resampling routine in aac67da7d27a26ce01ca7dc8491e6766ee1e318b, it sholud be resolved this issue.
dev-build: https://ci.appveyor.com/project/BambooTracker/bambootracker/builds/46095211/job/aqkaujmuukak8ce6/artifacts
