### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Release 0.6.0 does not open

### ISSUE THREAD

**Issue by Zexxerd** [BambooTracker/BambooTracker#479]
> #### Checklist
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.

---

## Bug Description

This is a variant of issue #477, discovered by @cxong. When I try to open the application, it says "The application “BambooTracker” can’t be opened." and no further action is taken.
 
## How to reproduce

1. Open BambooTracker
2. ???
3. Profit?

## System Information

- **Operating System**: macOS Monterey, Version 12.6.1
- **BambooTracker Version**: v0.6.0
- **Build Type**: Official

**Comment by Zexxerd** [comment]
For some reason, all I had to do to fix it was enter the app directory, cd into its MacOS folder, and run `chmod +x BambooTracker`...

**Comment by rerrahkr** [comment]
It may be that the Appveyor binary was decompressed and recompressed on my windows. Does it work fine with the original Appveyorbuild? https://ci.appveyor.com/project/rerrahkr/bambootracker-tmp/builds/46046698/job/l9k8ce6vsxcp7ri7/artifacts

**Comment by rerrahkr** [comment]
Sorry for the repeated confirmation. I tried to build without Homebrew in the forked repository.
https://github.com/rerrahkr/BambooTracker-tmp/releases/tag/v0.0.1
@Zexxerd @cxong  Does this still need to run `chmod +x BambooTracker`?

**Comment by cxong** [comment]
the forked repo works

**Comment by rerrahkr** [comment]
I built[ 0.6.0](https://github.com/rerrahkr/BambooTracker-tmp/releases/tag/v0.6.0) with the forked repositories. The binaries have been replaced with [the release page](https://github.com/BambooTracker/BambooTracker/releases/tag/v0.6.0). If the binary on the release page still does not work, it may be necessary to rebuild it again, including the binaries for other platforms.

**Comment by rerrahkr** [comment]
I fixed buid flows in #480. In the next release of automatic deployment, this issue should be resolved.
