### ISSUE TITLE
[Windows|macOS|Linux|BSD] - font size keeps defaulting back to 12pt in appearance settings

### ISSUE THREAD

**Issue by staticanimal** [BambooTracker/BambooTracker#481]
[✓] I am reporting exactly 1 bug with this issue.
[✓] This bug hasn't already been reported.
[X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

there is a bug causing the size of every customizable font within the appearance menu to get reset to 12pt every single time the configuration window is closed and reopened, forcing the user to set their preferred font size settings again upon changing the program's configuration to avoid them getting reset upon applying the new settings.

## How to reproduce

1. open program configuration
2. change font size
3. apply settings
4. close menu
5. reopen menu

## System Information

- **Operating System**: Windows 11
- **BambooTracker Version**: 0.6.0
- **Build Type**: Official

**Comment by rerrahkr** [comment]
Thank you for your report, I fixed it in 9ef6111. You can check it in dev build. https://ci.appveyor.com/project/BambooTracker/bambootracker/builds/46131192/job/xx7liqg11r1up797
