### ISSUE TITLE
[Feature] - .deb version

### ISSUE THREAD

**Issue by MesaBlack** [BambooTracker/BambooTracker#488]
> #### Checklist
> 
> - [ ] debian version
> 
> - [x] I'm requesting exactly 1 feature with this issue.
> - [x] This feature hasn't already been requested.
> - [x] This feature hasn't already been implemented in the latest development build.

--- I'm requesting a .deb version so I can use it with ease on my chromebook.

**Comment by MesaBlack** [comment]
erm...

**Comment by MesaBlack** [comment]
Yeah... maybe a .deb version like with gb studio?

**Comment by rerrahkr** [comment]
Sorry for late reply.
Actually, I am not familiar enough with linux and how to create a deb file, so I can't help you right now. 
You can use apt to install it instead. https://github.com/BambooTracker/BambooTracker#debian--ubuntu

**Comment by MesaBlack** [comment]
I have done that and said yes to it, but I dunno how to open it. Especially through penguin on a chromebook.

**Comment by rerrahkr** [comment]
Does typing `BambooTracker` not start the application?

**Comment by MesaBlack** [comment]
lemme see: just "BambooTracker", and it WORKED!

**Comment by MesaBlack** [comment]
Now, how do I get music tracks from a pc-98 game (.hdi file) into the editor?

**Comment by rerrahkr** [comment]
BambooTracker is not a data analysis software, but a music composition software. It does not have the ability to load song data from hdi.
For tone data, it may be possible to run an emulator or use analysis software to read extracted files.
I don't know much about hdi files, so I think you'd get better information if you ask in the PC-98 community somewhere.
