### ISSUE TITLE
[Windows|macOS|Linux|BSD] - Incompatible with RtAudio 6.0.0

### ISSUE THREAD

**Issue by OPNA2608** [BambooTracker/BambooTracker#492]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

[RtAudio 6.0.0 released](https://github.com/thestk/rtaudio/releases/tag/6.0.0), among other things featuring a
> - major API changes concerning error handling ... C++ exceptions no longer used

```
audio/audio_stream_rtaudio.cpp: In member function 'virtual bool AudioStreamRtAudio::initialize(uint32_t, uint32_t, uint32_t, const QString&, const QString&, QString*)':
audio/audio_stream_rtaudio.cpp:82:16: error: 'RtAudioError' does not name a type; did you mean 'RtAudioErrorType'?
   82 |         catch (RtAudioError& error) {
      |                ^~~~~~~~~~~~
      |                RtAudioErrorType
audio/audio_stream_rtaudio.cpp:83:17: error: 'error' was not declared in this scope; did you mean 'perror'?
   83 |                 error.printMessage();
      |                 ^~~~~
      |                 perror
```

## How to reproduce

1. Have RtAudio 6.0.0
2. Build with `qmake CONFIG+=system_rtaudio` or `cmake -DSYSTEM_RTAUDIO=ON`

## System Information

- **Operating System**: NixOS 23.05
- **BambooTracker Version**: 0.6.1
- **Build Type**: package manager

**Comment by ehaupt** [comment]
Thank you for tracking and reporting this. The FreeBSD port of rtaudio was recently updated which in turn broke the FreeBSD port of bambootracker.

Here is a full build log from the FreeBSD build cluster:
https://pkg-status.freebsd.org/beefy5/data/124i386-default/e5b71726cc79/logs/bambootracker-0.6.1_1.log

**Comment by ehaupt** [comment]
@rerrahkr thank you. Could you maybe tag `v0.6.2` this would help package maintainers :smile_cat:
