### ISSUE TITLE
[Linux] - Cannot open libgcc_s.so.1

### ISSUE THREAD

**Issue by defensem3ch** [BambooTracker/BambooTracker#498]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

When running BambooTracker 0.6.3 on Linux Mint, I am getting the following error:
`nix-user-chroot: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory`

## System Information

- **Linux Mint 21.2** 
- **BambooTracker v0.6.3** 
- **Official**

**Comment by rerrahkr** [comment]
Thank you for your report. I can replicate this in my environment, so I try to see why it happens.

**Comment by rerrahkr** [comment]
I have just replaced "BambooTracker-v0.6.3-linux-64bit.zip". You should now be able to run it.
