### ISSUE TITLE
[macOS] Release binary lacks executable permissions

### ISSUE THREAD

**Issue by djmaximum17** [BambooTracker/BambooTracker#502]
any idea why the MacOS build doesn't work on MacOS 14 on ARM64 Macs? I've tried everything I could think of and even the unix executable doesn't show up correctly and can't open it in the turmenal.
![Screenshot 2024-03-11 at 5 16 56 PM](https://github.com/BambooTracker/BambooTracker/assets/61179162/90974339-5ce7-4e8d-b325-2e7367753f55)
![Screenshot 2024-03-11 at 5 33 53 PM](https://github.com/BambooTracker/BambooTracker/assets/61179162/ee465183-320a-4f7a-83de-bcf9c4964b4d)
![Screenshot 2024-03-11 at 5 41 40 PM](https://github.com/BambooTracker/BambooTracker/assets/61179162/5eca87ec-4e14-4a06-b504-27c2df7bd855)
![Screenshot 2024-03-11 at 6 37 30 PM](https://github.com/BambooTracker/BambooTracker/assets/61179162/f9665860-93cc-443f-baed-d3e03f496777)

**Comment by OPNA2608** [comment]
Problem appears to be that ZIP format does not preserve UNIX file permissions to the necessary degree for this to work. It's maybe possible with special attribute additions to the format, but this seems to rely on the extractor actually supporting them.

@djmaximum17 Could you check if [this archive](https://github.com/BambooTracker/BambooTracker/files/14666893/BambooTracker-v0.0.0-macos-64bit.tar.gz) works for you without any post-unpack fixup like that? (https://github.com/OPNA2608/BambooTracker/commit/021272fd27479e89a9c6ad49fcc4ac5f8124843e)
