### ISSUE TITLE
[Windows] - Reflect Instrument Number Change does not work between modules.

### ISSUE THREAD

**Issue by Esmerea** [BambooTracker/BambooTracker#515]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description
When "Reflect Instrument Number Change" is active in the general configuration, it works for the module/song you are currently editing. However when you switch to a new song in the same Bamboo Tracker file, these changes are not reflected. This causes the instrument sounds to be incorrect for all other songs than the one you began on.

## How to reproduce

1. Create a Bamboo Tracker file with two songs/modules in it (called Song A and B here).
2. Check Reflect Instrument Number Change in settings
3. Move instruments in Song A, these are reflected in Song A.
4. Switch to Song B - the instrument number changes are not reflected.

## System Information
- Windows 11
- BT 0.6.4
- Windows 64 build from github.

**Comment by rerrahkr** [comment]
Originally, it was intended to replace all songs, but it became too slow, so it now works only for the current song.
However, the current behavior also causes this confusion, so maybe it should be done for all songs...
